In [1]:
# creating array
import array
a = array.array('i',[5,6,-7,8])
print('The array elements are : ')
for element in a:
    print(element)

The array elements are : 
5
6
-7
8


In [2]:
# creating an array - v2.0
from array import*
a = array('i',[5,6,7,8])
print('The array elements are:')
for element in a:
    print(element)

The array elements are:
5
6
7
8


In [4]:
# creating an array with characters
from array import*
arr = array('u',['a','b','c','d','e'])
print('The array elements are : ')
for ch in arr :
    print(ch)

The array elements are : 
a
b
c
d
e


In [5]:
# Creating one array from another array
from array import *
arr1 = array('d',[1.5,2.5,-3.5,4])

# use same type code and multiply each element of arr1 with 3
arr2 = array(arr1.typecode,(a*3 for a in arr1))
print('The arr2 elements are : ')
for i in arr2:
    print(i)

The arr2 elements are : 
4.5
7.5
-10.5
12.0


In [6]:
# accessing elements of an array using index
from array import *
x = array('i',[10,20,30,40,50])
# find number of elements in the array
n = len(x)
# display array elements using indexing
for i in range(n):        # repeat from 0 to n-1
    print(x[i],end=' ')

10 20 30 40 50 

In [7]:
# accessing elements of an array using index -v 2.0
from array import *
x = array('i',[10,20,30,40,50])
# find number of elements in the array
n = len(x)
# display array elements using indexing
i = 0
while i < n:
    print(x[i],end=' ')
    i += 1

10 20 30 40 50 

In [8]:
# create array y with elements from 1 st to 3 rd from x
y = x[1:4]
print(y)
# create array y with elements from 0 th till the last element in x
y = x[0:]
print(y)
# create array y with elements from 0 th to 3rd from x
y = x[:4]
print(y)
# create y with last 4 elements from x
y = x[-4:]
print(y)

# create y with last 4 th element and with [-4-(-1) = -3] elements
# towards right
y = x[-4:-1]
print(y)

# create y with 0th to 7th elements from x.
# stride 2 means, after 0th elemnt , retrieve every 2nd element from x
y = x[0:7:2]
print(y)

array('i', [20, 30, 40])
array('i', [10, 20, 30, 40, 50])
array('i', [10, 20, 30, 40])
array('i', [20, 30, 40, 50])
array('i', [20, 30, 40])
array('i', [10, 30, 50])


In [9]:
# using slicing to display elements of an array
from array import *
x = array('i',[10,20,30,40,50,60,70])
# display elements from 2 nd to 4 th only
for i in x[2:5]:
    print(i)

30
40
50


In [10]:
# operations on arrays
from array import * 
# create an array with int values
arr = array('i',[10,20,30,40,50])
print('Original array : ',arr)

# append 30 and 60 to the array arr
arr.append(30)
arr.append(60)
print('After appending 30 and 60 : ',arr)

# insert 99 at position number 1 in arr
arr.insert(1,99)
print('After inserting 99 in 1st positions : ',arr)

# remove an element from arr
arr.remove(20)
print('After removing 20 : ', arr)

# remove last element using pop() method
n = arr.pop()
print('Array after using pop() : ',arr)
print('Popped element : ',n)

# finding position of element using index() method
n = arr.index(30)
print('First occurence of element 30 is at : ',n)

# convert an array into a list using tolist() method
lst = arr.tolist()
print('List : ',lst)
print('Array : ',arr)


Original array :  array('i', [10, 20, 30, 40, 50])
After appending 30 and 60 :  array('i', [10, 20, 30, 40, 50, 30, 60])
After inserting 99 in 1st positions :  array('i', [10, 99, 20, 30, 40, 50, 30, 60])
After removing 20 :  array('i', [10, 99, 30, 40, 50, 30, 60])
Array after using pop() :  array('i', [10, 99, 30, 40, 50, 30])
Popped element :  60
First occurence of element 30 is at :  2
List :  [10, 99, 30, 40, 50, 30]
Array :  array('i', [10, 99, 30, 40, 50, 30])


In [12]:
# a python program to storing student's marks into an array and finding total marks and percentage of marks.
from array import *
# accept marks as a string
str = input('Enter marks : ').split(' ')
# store the marks into 'marks' array
marks =[int(num) for num in str]
# display the marks and find total
sum = 0
for x in marks:
    print(x)
    sum += x
print('Total marks : ',sum)
# display percentage
n = len(marks)      # n = no. of elements in marks array
percentage = sum/n
print('Percentage : ',percentage)

Enter marks : 50 56 75 67 45
50
56
75
67
45
Total marks :  293
Percentage :  58.6


In [13]:
from array import *
# accept marks as a string
str = input('Enter marks : ').split(' ')
# store the marks into 'marks' array
marks = array('i' ,[int(num) for num in str])
print(marks)
# display the marks and find total
sum = 0
for x in marks:
    print(x)
    sum += x
print('Total marks : ',sum)
# display percentage
n = len(marks)      # n = no. of elements in marks array
percentage = sum/n
print('Percentage : ',percentage)

Enter marks : 50 56 75 67 45
array('i', [50, 56, 75, 67, 45])
50
56
75
67
45
Total marks :  293
Percentage :  58.6


In [15]:
# sorting an array using Bubble sort technique
from array import *
# create an empty array to store integers
x = array('i',[])
# store elements into the array x
print('How many elements ?',end='')
n = int(input())  # accept input into n 
for i in range(n):  # repeat for n times
    print('Enter element : ',end='')
    x.append(int(input()))  # add the element to the array x
print('Original array : ',x)

# bubble sort 
flag = False  # when swapping is done , flag becomes True
for i in range(n-1):   # i is from 0 to n-1
    for j in range(n-1-i):  # j is from 0 to one element lesser than i
        if x[j] > x[j+1]:   # if first element is bigger than the second one
            t = x[j]        # swap j and j+1 elements
            x[j] = x[j+1]
            x[j+1] = t
            flag = True     # swapping done , hence flag is True
    if flag == False:        # no swapping means arrays is in sorted order
        break               # come out of inner loop
    else:
        flag = False        # assign initial value to flag
print('Sorted array = ',x)            

How many elements ?5
Enter element : 1
Enter element : 5
Enter element : 4
Enter element : 3
Enter element : 2
Original array :  array('i', [1, 5, 4, 3, 2])
Sorted array =  array('i', [1, 2, 3, 4, 5])


In [16]:
from array import *
# create an empty array to store integers
x = array('i',[])
# store elements into the array x
print('How many elements ?',end='')
n = int(input())  # accept input into n 
for i in range(n):  # repeat for n times
    print('Enter element : ',end='')
    x.append(int(input()))  # add the element to the array x
print('Original array : ',x)

# bubble sort 
flag = False  # when swapping is done , flag becomes True
for i in range(n-1):   # i is from 0 to n-1
    for j in range(n-1-i):  # j is from 0 to one element lesser than i
        if x[j] > x[j+1]:   # if first element is bigger than the second one
            
            x[j] , x[j+1] = x[j+1] , x[j]    # swap j and j+1 elements
            
            flag = True     # swapping done , hence flag is True
    if flag == False:        # no swapping means arrays is in sorted order
        break               # come out of inner loop
    else:
        flag = False        # assign initial value to flag
print('Sorted array = ',x)            

How many elements ?5
Enter element : 1
Enter element : 5
Enter element : 4
Enter element : 3
Enter element : 2
Original array :  array('i', [1, 5, 4, 3, 2])
Sorted array =  array('i', [1, 2, 3, 4, 5])


In [1]:
# Searching an array for an element using sequential search
from array import*
# create an empty array to store integers
x = array('i',[])

# store elements into the array x
print('How many elements ?',end='')
n = int(input())       # accept input into n

for i in range(n):     #repeat for n times
    print('Enter element : ',end='')
    x.append(int(input()))   # add element to the array x

print('Original array :',x)

print('Enter element to search : ',end='')
s = int(input())             # accept element to be searched

# linear search  or sequential search
flag = False        # this becomes True if element is found

for i in range(len(x)):  # repeat i from 0 to no. of elements
    if s == x[i]:
        print('Found at position =',i+1)
        flag =True
if flag == False:
    print('Not found in the array')

How many elements ?5
Enter element : 20
Enter element : 40
Enter element : 20
Enter element : 55
Enter element : 10
Original array : array('i', [20, 40, 20, 55, 10])
Enter element to search : 20
Found at position = 1
Found at position = 3


In [2]:
# searching an array for an element -v2.0 using index() method
from array import *
# create an empty array to store integers
x = array('i',[])

# store elements into array x
print('How many elements ? ',end='')
n = int(input())  # accept input into n

for i in range(n):            # repeat for n times
    print('Enter elements : ',end='')
    x.append(int(input()))   # add element to the array x

print('Original array : ',x)
print('Enter element to search : ',end='')
s = int(input())    # accept element to be searched

# index() method gives the location of the element in the array 
try:
    pos = x.index(s)
    print('Found at Position = ',pos+1)

except ValueError:   # if element not found then the ValueError will rise
    print('Not found in the array')    

How many elements ? 5
Enter elements : 20
Enter elements : 40
Enter elements : 20
Enter elements : 55
Enter elements : 10
Original array :  array('i', [20, 40, 20, 55, 10])
Enter element to search : 20
Found at Position =  1


In [3]:
# creating single dimensional array using numpy
import numpy
arr = numpy.array([10,20,30,40,50])  #create array
print(arr)  # display array

[10 20 30 40 50]


In [4]:
# creating single dimensional array using numpy - v2.0
import numpy as np
arr = np.array([10,20,30,40,50]) #create array
print(arr)  #display array


[10 20 30 40 50]


In [5]:
# creating single dimensional array using numpy - v3.0
from numpy import *
arr = array([10,20,30,40,50])   #create array
print(arr)  # display array

[10 20 30 40 50]


In [6]:
# creating an array with characters
from numpy import *
arr = array(['a','b','c','d']) # create array
print(arr)  # display array

['a' 'b' 'c' 'd']


In [7]:
# creating an array with characters
from numpy import *
#create array
arr = array(['Delhi','Hyderabad','Mumbai','Ahmedabad'],dtype = str)
print(arr)  # display array

['Delhi' 'Hyderabad' 'Mumbai' 'Ahmedabad']


In [8]:
# creating an array with characters
from numpy import *
#create array
arr = array(['Delhi','Hyderabad','Mumbai','Ahmedabad'])
print(arr)  # display array

['Delhi' 'Hyderabad' 'Mumbai' 'Ahmedabad']


In [9]:
# creating an array from another array 
from numpy import*
a = array([1,2,3,4,5])  # original array
b = array(a)            # create b from a using array() function
c = a                   # create c by assinging a to c
# display arrays
print('a = ',a)
print('b = ',b)
print('c = ',c)

a =  [1 2 3 4 5]
b =  [1 2 3 4 5]
c =  [1 2 3 4 5]


In [12]:
# creating an array using linspace()
from numpy import *

# divide 0 to 10 into 5 parts and take those points in the array
a = linspace(0,10,5)
b = linspace(0,10)# default n is 50
c = linspace(0,10,10)
print('a = ',a)
print('b = ',b)
print('c = ',c)

a =  [ 0.   2.5  5.   7.5 10. ]
b =  [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
c =  [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [13]:
# creating an array using logspace()
from numpy import *

# divide the range : 10 power 1 to 10 power 4 into 5 equal parts
# and take those point in the array
a = logspace(1,4,5) 
b = logspace(1,4)   # default n is 50

# find no.of elements in a
n = len(a)

# repeat from 0 to n-1 times
for i in range(n):
    print('%.1f'%a[i] , end=' ')   # display 1 digit after decimal points
print()
print(b)

10.0 56.2 316.2 1778.3 10000.0 
[   10.            11.51395399    13.25711366    15.26417967
    17.57510625    20.23589648    23.29951811    26.82695795
    30.88843596    35.56480306    40.94915062    47.14866363
    54.28675439    62.50551925    71.9685673     82.86427729
    95.40954763   109.8541142    126.48552169   145.63484775
   167.68329368   193.06977289   222.29964825   255.95479227
   294.70517026   339.32217719   390.69399371   449.8432669
   517.94746792   596.36233166   686.648845     790.60432109
   910.29817799  1048.11313415  1206.79264064  1389.49549437
  1599.85871961  1842.06996933  2120.95088792  2442.05309455
  2811.76869797  3237.45754282  3727.59372031  4291.93426013
  4941.71336132  5689.86602902  6551.2855686   7543.12006335
  8685.11373751 10000.        ]


In [15]:
# creating arrays using arange() function
from numpy import * 
print(arange(10))
print(arange(5,10))
print(arange(1,10,3))
print(arange(10,1,-1))
print(arange(0,10,1.5))


[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[1 4 7]
[10  9  8  7  6  5  4  3  2]
[0.  1.5 3.  4.5 6.  7.5 9. ]


In [16]:
# creating an array with even numbers upto 10
from numpy import *

# create an array using arange() function
a = arange(2,11,2)
print(a)

[ 2  4  6  8 10]


In [17]:
# creating arrays using zeros() and ones()
from numpy import *
a = zeros(5,int)
print(a)
# default datatype is float
b = ones(5)
print(b)

[0 0 0 0 0]
[1. 1. 1. 1. 1.]


In [18]:
# maathematical operations on arrays
# import all from numpy module
from numpy import *

# create a numpy array using array() function
arr = array([10,20,30.5,-40])
print('Original array : ',arr)

# do arithmetic operations on the elements of the array
print("After adding 5 : ",arr+5)
print('After substracting 5 : ',arr-5)
print('After multiplying with 5 : ',arr*5)
print('After dividing with 5 : ',arr/5)
print('After modulus with 5 : ',arr%5)

# we can use the arrays in expressions also
print("Expression value : ",(arr+5)**2-10)

# do some math functions
print("Sin values : ",sin(arr))
print("Cos values : ",cos(arr))
print("Tan values : ",tan(arr))
print("Biggest element : ",max(arr))
print("Smallest element : ",min(arr))
print("Sum of all element : ",sum(arr))
print("Average of all elements : ",mean(arr))

Original array :  [ 10.   20.   30.5 -40. ]
After adding 5 :  [ 15.   25.   35.5 -35. ]
After substracting 5 :  [  5.   15.   25.5 -45. ]
After multiplying with 5 :  [  50.   100.   152.5 -200. ]
After dividing with 5 :  [ 2.   4.   6.1 -8. ]
After modulus with 5 :  [0.  0.  0.5 0. ]
Expression value :  [ 215.    615.   1250.25 1215.  ]
Sin values :  [-0.54402111  0.91294525 -0.79312724 -0.74511316]
Cos values :  [-0.83907153  0.40808206  0.60905598 -0.66693806]
Tan values :  [ 0.64836083  2.23716094 -1.30222389  1.11721493]
Biggest element :  30.5
Smallest element :  -40.0
Sum of all element :  20.5
Average of all elements :  5.125


In [19]:
# to know the result of comparing two arrays
from numpy import *
a = array([1,2,3,0])
b = array([0,2,3,1])

c = a == b
print('Result of a == b',c)
c = a > b
print('Result of a>b',c)
c = a <= b
print('Result of a<=b',c)

Result of a == b [False  True  True False]
Result of a>b [ True False False False]
Result of a<=b [False  True  True  True]


In [20]:
# using any() and all() functions
from numpy import *
a = array([1,2,3,0])
b = array([0,2,3,1])

c = a > b
print('Result of a>b : ',c)

print('Check if any one element is true : ',any(c))
print('Check if all elements are true : ',all(c))

if(any(a>b)):
    print('a contains atleast one element greater than those of b')

Result of a>b :  [ True False False False]
Check if any one element is true :  True
Check if all elements are true :  False
a contains atleast one element greater than those of b


In [1]:
# using logical_and() , logical_or() ,logical_not()
from numpy import *
a = array([1,2,3],int)
b = array([0,2,3],int)

c = logical_and(a>0 , a<4)
print(c)

c = logical_or(b>=0 ,b==1)
print(c)

c = logical_not(b)
print(c)

[ True  True  True]
[ True  True  True]
[ True False False]


In [2]:
a = array([10,21,30,40,50])
c = where(a%2==0 ,a,0)
print(c)

[10  0 30 40 50]


In [3]:
# using where() function
from numpy import *
a = array([10,20,30,40,50],int)
b = array([1,21,3,40,51],int)
# if a>b then take element from a else from b
c = where(a>b,a,b)
print(c)

[10 21 30 40 51]


In [4]:
# Python program to retrieve non zero element from an array
# using nonzero() function 
a = array([1,2,0,-1,0,6],int)
# retrieve indexes of nonzero elements from a
c = nonzero(a)

#display indexes
for i in c:
    print(i)

# display the elements
print(a[c])

[0 1 3 5]
[ 1  2 -1  6]


In [5]:
# aliasing an array
from numpy import *
a = arange(1,6)  # create a with elements 1 to 5
b = a            # give another name b to a 

print('Original array : ',a)
print('Alias array :',b)

b[0] = 99 # modify 0th element of b
print("After modification : ")
print('Original array : ',a)
print('Alias array :',b)

Original array :  [1 2 3 4 5]
Alias array : [1 2 3 4 5]
After modification : 
Original array :  [99  2  3  4  5]
Alias array : [99  2  3  4  5]


In [6]:
# creating view for an array
# shallow copying
from numpy import *
a = arange(1,6)      # create a with elements 1 to 5
b = a.view()         # create a view of a and call it b
print('Original array :',a)
print('New array',b)

b[0] = 99           # modify 0th element of b
print("After modification :")
print('Original array : ',a)
print('New array : ',b)

Original array : [1 2 3 4 5]
New array [1 2 3 4 5]
After modification :
Original array :  [99  2  3  4  5]
New array :  [99  2  3  4  5]


In [7]:
# copying an array
from numpy import *
a = arange(1,6)      # create a with elements 1 to 5
b = a.copy()         # create a copy of a and call it b

print('Original array : ',a)
print('New array : ',b)

b[0] = 99            # modify 0 th element
print('After modification :')
print("Original array : ",a)
print('New array : ',b)

Original array :  [1 2 3 4 5]
New array :  [1 2 3 4 5]
After modification :
Original array :  [1 2 3 4 5]
New array :  [99  2  3  4  5]


In [9]:
# slicing an array 
from numpy import *
# create array a with elements 10 to 15 
a = arange(10,16)
print(a)

# retrieve from 1st to one element prior to the 6 th element in steps of 2
b = a[1:6:2]
print(b)

# retrieve all elements from a
b = a[::]
print(b)

# retrieve from 6-2 = 4th element to one element prior to 2 nd element in 
# decreasing step size
b = a[-2:2:-1]
print(b)
# retrieve from 0th to one element prior to 4 th element(6-2 = 4th)
b = a[:-2:]
print(b)

[10 11 12 13 14 15]
[11 13 15]
[10 11 12 13 14 15]
[14 13]
[10 11 12 13]


In [10]:
# indexing an array
from numpy import *
# create array a with elements 10 to15
a = arange(10,16)
print(a)
# retrieve from 1st element prior to the 6 th element in steps of 2
a = a[1:6:2]
print(a)

# display elements using indexing
i = 0
while(i<len(a)):
    print(a[i])
    i += 1

[10 11 12 13 14 15]
[11 13 15]
11
13
15


In [11]:
# array with  1 row
arr1 =array([1,2,3,4,5])
print(arr1)     #display
# array with 1 coloumn
arr2 = array([10,
              20,
              30,
              40])
print(arr2)

[1 2 3 4 5]
[10 20 30 40]


In [12]:
# create a 2D array with 2 rows and 3 columns in each row
arr2 = array([[1,2,3],
              [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [15]:
from numpy import *
arr3 = array([[[1,2,3],[4,5,6]],
              [[1,1,1],[1,0,1]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 1 1]
  [1 0 1]]]


In [1]:
# ndim attribute
from numpy import *
arr1 = array([1,2,3,4,5])   #  1D array
print(arr1.ndim)

1


In [2]:
arr2 = array([[1,2,3],[4,5,6]])  # 2D array with 2 rows and 3 element
print(arr2.ndim)

2


In [3]:
# shape attribute
arr1 = array([1,2,3,4,5])
print(arr1.shape)    # it gives rows and columns of array in the form of tuple

(5,)


In [7]:
arr2 = array([[1,2,3],[4,5,6]])
print(arr2.shape)
arr2.shape = (3,2)  # change shape of arr2 to 3 rows and 2 coloumns
print(arr2)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [8]:
# size attribute       # total number of elements
print(arr1.size)
print(arr2.size)

5
6


In [9]:
# itemsize attribute  # memorysize in bytes
arr1 = array([1,2,3,4,5])
print(arr1.itemsize)
arr2 = array([1.1,2.2,3.5,4,5.0])
print(arr2.itemsize)

4
8


In [11]:
# dtype attribute           # datatype of elements
arr1 = array([1,2,3,4,5])   
print(arr1.dtype)
arr2 = array([1.1,2.2,3.5,4,5.0])
print(arr2.dtype)

int32
float64


In [12]:
# nbytes attribute   # gives total number of bytes occupied by an array
# nbytes = arr.size * arr.itemsize
arr2 = array([[1,2,3],[4,5,6]])
print(arr2.nbytes)

24


In [13]:
# reshape() method
arr1 = arange(10)     # 1D array with 10 elements
print(arr1)
arr1 = arr1.reshape(2,5)        # change shape as 2 rows and 5 cols
print(arr1)
arr1 = arr1.reshape(5,2)        # change shape as 5 rows and 2 cols
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
# flatten method  
arr2 = array([[1,2,3],[4,5,6]])
print(arr2)
arr2 = arr2.flatten()
print(arr2)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [15]:
# multidimensional array
#array() fuction
a = array([1,2,3,4,5])        # creates a 1D array with 1 row
a =array([[1,2,3],[4,5,6]])   # creates a 2D array with 2 rows and 3 cols
print(a)

[[1 2 3]
 [4 5 6]]


In [16]:
# ones() and zeros() fuctions        # to create arrays with all elements 1 and 0
# ones((r,c),dtype)
a = ones(5,float)
print(a)
a = ones((3,4),float)
print(a)
b= zeros(5,int)
print(b)
b = zeros((3,4),int)
print(b)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
# eye() function      # diagonal elements are 1
# eye(n,dtype)
a = eye(3)      # default datatype is float
print(a)
b = eye(5)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# reshape() function
# rehape(arrayname,(n,r,c))
# n no. of arrays in result 
# r = rows
# c = coloumn

In [18]:
a = array([1,2,3,4,5,6])
b = reshape(a,(2,3))
print(b)
b = reshape(a,(3,2))
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
a = arange(12)
print(a)
b = reshape(a,(2,3,2))   # 2 arrays with 3 rows and 2 colomns
print(b)
print('_'*10)
b = reshape(a,(3,2,2))   # 3 arrays with 2 rows and 2 columns
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
__________
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [21]:
# retrieving the elements from a 2D array using indexing
from numpy import*
# create a 2D array with 3 rows and 3 cols
a = array([[1,2,3],[4,5,6],[7,8,9]])

# display only rows
for i in range(len(a)):
    print(a[i])
    
# display element by element
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j],end=' ')

[1 2 3]
[4 5 6]
[7 8 9]
123456789

In [25]:
# retrieving the elements from a 3D array using indexing
# create a 3D array with size 2x2x3
a = array([[[1,2,3],
           [4,5,6]],
           
           [[7,8,9],
           [10,11,12]]]) 
# display element by element
for i in range(len(a)):
    for j in range(len(a[i])):
        for k in range(len(a[i][j])):
            print(a[i][j][k],end='\t')
        print()
    print()


1	2	3	
4	5	6	

7	8	9	
10	11	12	



In [26]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a = reshape(a,(3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
print(a[: , :])
print(a[:])
print(a[::])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print(a[0,:])  # 0 th row
print(a[:,0])  # 0 th col

[1 2 3]
[1 4 7]


In [30]:
print(a[0:1,0:1])  # 0 th row and 0 th  column

[[1]]


In [31]:
print(a[1:2,1:2])  # 1 st row and 1 st column

[[5]]


In [32]:
print(a[2:3,2:3])  # 2 nd row and 2 nd column
print(a[2:3,1:2])  # 2nd row and 1 st column

[[9]]
[[8]]


In [33]:
a = reshape(arange(11,36,1),(5,5))
print(a)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [34]:
print(a[0:2,0:3]) 

[[11 12 13]
 [16 17 18]]


In [35]:
print(a[2:4,3:5])

[[24 25]
 [29 30]]


In [36]:
print(a[0:2,2:])

[[13 14 15]
 [18 19 20]]


In [37]:
print(a[2:,3:])

[[24 25]
 [29 30]
 [34 35]]


In [38]:
# Matrices in numpy
# matrix-name = matrix(2D array or string)
from numpy import *
arr = array([[1,2,3],[4,5,6]])
a = matrix(arr)
print(a)    

[[1 2 3]
 [4 5 6]]


In [39]:
a = matrix([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [40]:
str = '1 2 ; 3 4 ; 5 6' # semicolons are used to seperate rows
b = matrix(str)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [41]:
b = matrix('1 2; 3 4 ; 5 6')
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [42]:
# diagonal() of matrix
a = matrix('1 2 3 ; 4 5 6 ; 7 8 9')  #3x3 matrix
print(a)
d = diagonal(a)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [43]:
# maximum and minimum elements
big = a.max()
print(big)

small = a.min()
print(small)

9
1


In [44]:
# sum and average of elements
print(a.sum())
print(a.mean())

45
5.0


In [45]:
# products of elements
#prod(0) returns product of elements in each column
#prod(1) returns product of elements in each row
m = matrix(arange(12).reshape(3,4))
print(m)
a = m.prod(0)
b = m.prod(1)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0  45 120 231]]
[[   0]
 [ 840]
 [7920]]


In [46]:
# sorting the matrix
m = matrix([[5,4,1],[2,7,0]])
print(m)
a = sort(m)             # row wise sorting
print(a)
b = sort(m ,axis = 0)   # column vise sorting
print(b)

[[5 4 1]
 [2 7 0]]
[[1 4 5]
 [0 2 7]]
[[2 4 0]
 [5 7 1]]


In [47]:
# transpose of matrix
m = matrix('1 2 3; 4 5 6 ;7 8 9')
print(m)
t = m.transpose()
print(t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [48]:
t1 = m.getT()         # transpose of matrix using getT()
print(t1)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [50]:
# a python program to get matrix from user and display its transpose
from numpy import*

# accept number of rows and columns into r ,c
r,c = [int(a) for a in input("Enter rows , columns : ").split(',')]

# accept matrix elements as a string into str
str = input("Enter matrix elements : \n")

# convert the string into matrix with size rxc
x = reshape(matrix(str),(r,c))
print('The original matrix :')
print(x)

print('Transpose of matrix :')
y = x.transpose()
print(y)

Enter rows , columns : 2,3
Enter matrix elements : 
1 2 3 4 5 6
The original matrix :
[[1 2 3]
 [4 5 6]]
Transpose of matrix :
[[1 4]
 [2 5]
 [3 6]]


In [51]:
# matrix Addition and Multiplication
a = matrix('1 2 3 ; 4 5 6')
b = matrix('2 2 2 ; 1 -1 2')
print(a)
print(b)
c = a + b
print(c)

[[1 2 3]
 [4 5 6]]
[[ 2  2  2]
 [ 1 -1  2]]
[[3 4 5]
 [5 4 8]]


In [52]:
d = a/b
print(d)

[[ 0.5  1.   1.5]
 [ 4.  -5.   3. ]]


In [53]:
# multiplication of matrix occurs according to rules of mathematics 
# row by column
# size of matrix if a = r1 x c1 b = r2 x c2 gives  r1xc2 iff c1 == r2
# 2 x 3 matrix into 3 x 2  matrix gives 2 x 2 matrix
a = matrix([[1,2,3],[4,5,6]])
print(a)
b = matrix([[1,0],[0,2],[1,-1]])
print(b)
c = a*b           # multiply a and b to get c
print(c)          # display the resultant matrix    

[[1 2 3]
 [4 5 6]]
[[ 1  0]
 [ 0  2]
 [ 1 -1]]
[[ 4  1]
 [10  4]]


In [54]:
# matrix multiplication
import sys
from numpy import *

# accept number of rows and no. of columns of first matrix r1 ,c1
r1 ,c1 =[int(a) for a in input("First matrix rows , cols :").split()]

# accept number of rows and no. of cols of second matrix r2,c2
r2 ,c2 =[int(a) for a in input("Second matrix rows , cols :").split()]

# test condition if c1 != r2 , then multiplication is not possible
if c1 != r2:
    print('Multiplication is not possible')
    sys.exit()       # terminate the program
    
# accept first matrix elements into a string str1
str1 = input("Enter first matrix elements : \n")

# convert str1 into matrix of size r1 x c1
x = reshape(matrix(str1),(r1,c1))

# accept second matrix elements as a string into str2
str2 = input('Enter second matrix elements : \n')

# convert str2 into matrix of size r2 x c2
y = reshape(matrix(str2),(r2,c2))

print("The product of matrix : ")
z = x * y
print(z)

First matrix rows , cols :2 3
Second matrix rows , cols :3 2
Enter first matrix elements : 
1 2 3 4 5 6 
Enter second matrix elements : 
1 0 0 2 1 -1
The product of matrix : 
[[ 4  1]
 [10  4]]


In [55]:
# random module
print(random.rand())   # will generate a random number between 0.0 and 1.0
a = random.rand(5)     # will create a 1D array with 5 random no.
print(a)
b = random.rand(2,3)   # will create a 2D array with 6 values in 2 rows and 3 column
print(b)

0.6361051893855216
[0.2851321  0.09002375 0.01427744 0.2488404  0.01195407]
[[0.87803848 0.64929154 0.01110025]
 [0.3663037  0.75253046 0.81813479]]
